### ISSUE TITLE
Show Volume Panel for Audio change

### ISSUE THREAD

**Issue by shrimqy** [LSafer/edgeseek#18]
It would be good if you could add a preference to show the system volume panel when changing the Audio. I could give it a shot if PRs are welcome.

**Comment by LSafer** [comment]
Added it to my TODO list 👍️

> I could give it a shot if PRs are welcome.

Until the app is stable enough, I am not confident I am able to manage PRs effectively.

**Comment by LSafer** [comment]
I just released [0.3-pre.5 https://github.com/LSafer/edgeseek/releases](https://github.com/LSafer/edgeseek/releases/tag/0.3-pre.5)

It has a new 'System Panel' option to show the system panel. Can you try it out and give me your thoughts?

**Comment by shrimqy** [comment]
Thank you, it works. Although, when I turn on the seek acceleration, sometimes it worked but mostly it would just pop up and do nothing as I seek. I can work without but it is a bit slow for my liking. Maybe you could add an increment preference?

You should also remove the onboarding from the navigation stack after the completion when you get time. 

Thanks again.

**Comment by LSafer** [comment]
> Thank you, it works.

You are welcome <3

> sometimes it worked but mostly it would just pop up and do nothing as I seek.

Can you please give me your device info? I works with my phone (Samsung Note 10+ LineageOS 22.1)

> Maybe you could add an increment preference

Sorry, I didn't understand what you are referring to 😶

> You should also remove the onboarding from the navigation stack after the completion when you get time.

Yep, I noticed that last week but was too lazy to fix it right away, then I forgot. 😆

**Comment by shrimqy** [comment]
My device is Mi10i, A15 PixelOs. I can give you the logs later if that helps. 

>Increment preference 

I meant having an option to give the user the amount to increase on seek progress? If that makes sense.

**Comment by LSafer** [comment]
> sometimes it worked but mostly it would just pop up and do nothing as I seek.

Sorry, I thought I understood this. Do you mean that audio is not changing or do you mean the system panel does not update?

> I meant having an option to give the user the amount to increase on seek progress? If that makes sense.

There is 'Sensitivity', is this what you are referring to?

**Comment by shrimqy** [comment]
> There is 'Sensitivity', is this what you are referring to?

Ok, my bad. I inherently thought that was the sensitivity of the trigger rather than the sensitivity of the seeker. 

Well after I cranked up the sensitivity, I wouldn't even need to use seek acceleration, Thank you.

> Sorry, I thought I understood this. Do you mean that audio is not changing or do you mean the system panel does not update?

The system panel would only pop up and the audio wouldn't change when the seek acceleration is enabled. After cranking up the sensitivity, the volume did change but the change was really small?

https://github.com/user-attachments/assets/d15a6b39-ea95-4516-ad5f-dcf52f3532a7

I hope that video helps you understand.

**Comment by LSafer** [comment]
This **might** be caused by the screen resolution. I will reevaluate some measurements to be based on the `dpi` of the device.

I hard coded a lot of values that suite my many phones but I guess hard coding pixels never a good idea.

For context, I had test the app on `Samsung Note 10+` with `~498 ppi density`
And your device is `Xiaomi Mi 10i` with `~395 ppi density`

**Comment by LSafer** [comment]
I just released [0.3-pre.6](https://github.com/LSafer/edgeseek/releases/tag/0.3-pre.6). Does it fix the issue?

**Comment by shrimqy** [comment]
Actually, no, it didn't fix the issue. Enabling the seek acceleration is still more or less the same. Keeping the sensitivity high works pretty well for now, as this isn't that much of a high priority or a breaking bug. Thank you.

**Comment by LSafer** [comment]
> Keeping the sensitivity high works pretty well for now

Do you think increasing the sensitivity slider range would fix the issue?

> this isn't that much of a high priority or a breaking bug. Thank you.

You are welcome <3. I still want to fix the issue but as they say, time is money, and I am a bit broke these days XD

**Comment by shrimqy** [comment]
>Do you think increasing the sensitivity slider range would fix the issue?

No, i mean it should've worked without increasing the range tbh because that is the whole point of the seek acceleration. There seems to be something else that is causing the issue although i haven't looked at the code, i will try to see if I can debug it.

>You are welcome <3. I still want to fix the issue but as they say, time is money, and I am a bit broke these days XD

Thank you. Sorry to hear that, I would love to donate if that helps, but I didn't see any donation box.

**Comment by LSafer** [comment]
> No, i mean it should've worked without increasing the range tbh because that is the whole point of the seek acceleration. There seems to be something else that is causing the issue although i haven't looked at the code, i will try to see if I can debug it.

You are right, debugging with the device that has the issue is easier. And thank you for considering debugging it yourself <3

> Thank you. Sorry to hear that, I would love to donate if that helps, but I didn't see any donation box.

No, not broke literally. It was a metaphor for having no time 😅
