### ISSUE TITLE
Swipe gestures not responding.

### ISSUE THREAD

**Issue by LatringDay** [LSafer/edgeseek#22]
Either I dont know how to use them or they just dont work. I assigned swife down to open status bar on centre right, lower right and centre and lower left edges but swiping doesn't work. I changed thickness, sensitivity too but to no use. 

I also tried changing "seek" option to nothing to not let it interfere with swipe actions but it still didnt work. 

The new update (03-pre.5 ) is amazing by the way I am loving double tap to own status bar but it would've been great to swipe down and open it. 

It is a CMF phone 1 running android 15.

**Comment by LSafer** [comment]
I might need to decrease the threshold for swipe gesture. But, first, do you feel vibration when touching the edge? This vibration indicates that the edge was touched even if no action was performed.

**Comment by LatringDay** [comment]
Okay I am going to sound like an idiot but it work when I tried again, maybe the last time i didnt really give it a quick enough go 

But the vibration is still not working even though the level of vibration is 100 I tried it on different intensities but I think vibration does not work at all like it does not respond when I touch or double click or try to swipe.

So basically nothing is working with regards to vibration but the swipe definitely is working.

What can be done to help the swiping gesture is to lower down the threshold a bit which will make it smoother as for now i have to throw my Finger along the edge at lightening speed to get it ti work which is not so Bad but it definitely poses a threat to phone slipping out of the Hand for a butterfinger like myself.

**Comment by LSafer** [comment]
> But the vibration is still not working even though the level of vibration is 100 I tried it on different intensities but I think vibration does not work at all like it does not respond when I touch or double click or try to swipe.

Maybe I need to change the type of vibration or maybe it is a permission that is missing 🤔

Can you confirm that your device has a functional vibration motor? It **might** be too weak for short one-shot vibrations.

> What can be done to help the swiping gesture is to lower down the threshold a bit which will make it smoother

Yes, I figured out that the app was not tested on lower display density (pixel per inch). I used hard coded pixel measurements which works on my phone but not phones with different density. I solution for this will be implemented in the next update.

**Comment by LatringDay** [comment]
> Maybe I need to change the type of vibration or maybe it is a permission that is missing 🤔
> 
> Can you confirm that your device has a functional vibration motor? It **might** be too weak for short one-shot vibrations.

A functional vibration motor ?? The best I can tell you is that when I receive an incoming call or when the alarm goes off, it vibrates pretty well. Did you mean something else?


> Yes, I figured out that the app was not tested on lower display density (pixel per inch). I used hard coded pixel measurements which works on my phone but not phones with different density. I solution for this will be implemented in the next update.


I will be eagerly waiting.

**Comment by LSafer** [comment]
> A functional vibration motor ?? The best I can tell you is that when I receive an incoming call or when the alarm goes off, it vibrates pretty well. Did you mean something else?

To be honest. I have no idea what might be the cause of this issue. I use a pretty straightforward (by the book) approach for running the vibration motor. Thus, I am trying to gather as much info as I can.

> I will be eagerly waiting.

I will try my best to not let you down 😅

**Comment by LatringDay** [comment]
>I will try my best to not let you down 😅

You have never🤟🏻

**Comment by LSafer** [comment]
I just released [0.3-pre.6](https://github.com/LSafer/edgeseek/releases/tag/0.3-pre.6). Does it fix the issue?

**Comment by LatringDay** [comment]
Swipe gesture is still not working for me. Out of like 100 tries i managed to expand status bar twice only. 

Tried with maximum senstivity and thickness but to no use.

**Comment by LSafer** [comment]
> Tried with maximum senstivity and thickness but to no use.

I guess it is time to introduce multiple types of sensitivity. The current sensitivity slider is a bit mislabeled. It only controls the seek sensitivity.

**Comment by LatringDay** [comment]
Honestly i dont know if it is practical. Somehow the sliding will always interfere with the actual sliding gesture. 
Or else I am an idiot and you have a solution. Either way its more than what I can ask for. This app is godly and it couldn't be better. 

And I wanna make a issue (feature request apparently). I recently watched a video on the channel "howtomen" on yt and saw an app called ubiki touch. Thats an app that can be inspiration for your project. It has tons of ideas to be worked upon and perhaps do even better than done there. Like manipulating the edge swipe - when diagonally up it open an app, when down launch a diff app, when held diagonally up, a diff command and so on. One of the best functionality that I personally found godlike was a navigation thing that came out of the edge when triggered to have a cursor for the top half of the screen where our thumb doesn't reach but something there needs to be tapped on. 

I believe it was made as a replica to Samsung one hand operation +. I haven't personally used it but watched a video on it and its awesome. Now the question remains - do you wanna take the development of this app towards that direction? If yes, I would love to make a new issue so that things stay clear and separate there. 

Edit : the link to the video that I saw ubiki touch on - https://youtu.be/hGsPpd0uIco

**Comment by LSafer** [comment]
Wow, that is an awesome idea. But, I guess I need to focus on making the app work perfectly in every device first and add basic actions (such as open an app or do an app action). I am planning on doing a lot in the app but "a lot" means a lot of work and design which means time consumption which requires time which I don't have at this stage of my life </3

**Comment by LatringDay** [comment]
Thats correct. I totally understand the time constraints you have. I am hopeful for the future.
