### ISSUE TITLE
[Bug] Audio controls doesn't work for Oppo/OnePlus devices.

### ISSUE THREAD

**Issue by PAFCicleStick** [LSafer/edgeseek#8]
The audio track seeking is only working if I toggle the on and off in the specified settings for it when app is open. Then if I closed the app it is not working anymore.

**Comment by LSafer** [comment]
I am currently investigating the issue 🧐

**Comment by LSafer** [comment]
Could you please give me the information of your device and android version? I was unable to reproduce the same issue in any of my devices! Plus, did you give the required permissions for the application? In newer versions of android, you have to open the app settings and allow 'restricted permissions' manually see: https://www.youtube.com/watch?v=IXtIPOuF64k

**Comment by PAFCicleStick** [comment]
Uhmm ok I will try to check the permission, thank you.

Device: Oppo Reno 4 4g
Model: CPH2113
Android Version: Android 12

**Comment by LSafer** [comment]
I am sorry this might take a while to fix... I am currently working on something that **might** fix the issue but since this is a hobby  project you might need to wait for the next weekend (mine is Friday and Saturday)

**Comment by PAFCicleStick** [comment]
That is alright, I am really greatful to you about taking this app and having time to fix things, truly I am greatful and have a nice day.

**Comment by PAFCicleStick** [comment]
I am sorry but I have to bother you again, I updated the app to the latest but the problem still persist. This log might help

![Image](https://github.com/user-attachments/assets/424535ab-86fb-432f-8365-44b03f1e4b88)
![Image](https://github.com/user-attachments/assets/720c5429-69c4-4ce0-afea-c76e1c483bfd)

**Comment by LSafer** [comment]
Yep, as I suspected, it is a permission thing. This might not take a while to fix. Since it is just adding a new permission request. But I am so exhausted right now I might leave it for tomorrow.

**Comment by LSafer** [comment]
And no, you are awesome to reach to me about an issue. I very much appreciate it <3

**Comment by LSafer** [comment]
I think I found the culprit?: https://www.reddit.com/r/oneplus/comments/1b69srj/oneplus_12_is_blocking_all_thirdparty_apps_from/

Since Oppo and Oneplus are essentially the same company, this might be the root cause.

Now to search for the fix...

**Comment by PAFCicleStick** [comment]
That would be an unfortunate issue as Oppo is not releasing any software update to older devices now. I don't think they will fix it I even have problem in bluetooth stuttering when using LDAC which is only fixed in newer OS in some devices.

**Comment by PAFCicleStick** [comment]
Also take a rest first have a nice day or night? Sleep well😁

**Comment by LSafer** [comment]
> That would be an unfortunate issue as Oppo is not releasing any software update to older devices now.

I guess it can be fixed in the app itself but it appears initially to require Accessibility permission which I don't want
to require people granting it. I might add a version (branch) of the app just for you that uses Accessibility permission on top
of the other permissions.

> I don't think they will fix it

I recommend to you using LineageOS. It is not the most stable thing but it gets the job done. All my phones are from 2019 and older
yet most are running Android 15 thanks to LineageOS and other custom ROMs

> I even have problem in bluetooth stuttering when using LDAC 

Typical Oppo/Oneplus issues

**Comment by LatringDay** [comment]
Im jumping out of nowhere and I apologise for that but holy moly, can I also adjust the seek bar of the audio playing ? 
Will it work on youtube revanced Background playback too?

**Comment by LSafer** [comment]
@LatringDay no no, he meant audio control 😆

**Comment by LSafer** [comment]
Adding these as a references: 

- https://github.com/home-assistant/android/issues/3840

**Comment by PAFCicleStick** [comment]
I tried to email the customer service of Oppo and what they said is the same as the solution you propsed. I don't think they will fixed this to all their devices, Oppo, Oneplus will need acessibility permission in this kind of apps. Well, that's it I will continue to used your app and I am really thankful because I can now dimmed my screen lower than before which is good when I am reading at night hahaahaha well more power and good health to you dear creator😁.

![Image](https://github.com/user-attachments/assets/eb4bae4b-44a9-4535-ade4-c9ff264e1c3e)

**Comment by LSafer** [comment]
Wow, you are super awesome. I was hesitant to reach to Oppo about the issue.

Might you please ask them for me about what is the name of the permission OnePlus/Oppo require? Specify that you want a developer to answer since typically a person from marketing is answering customer questions. I am pretty sure there is a custom propitiatory permission name that, when added, will fix the issue. That is why I tried to dig deep in the OnePlus decompiled framework code but sadly I got too dizzy and gave up too early.

Accessibility permission is the nuclear option and I really don't want to implement it unless there is really no other option.

**Comment by LSafer** [comment]
There **might** be an "illegal" way of doing it using reflection and bypassing the whole Oplus `AudioManagerExtImpl` but experimentation, trial and error is not an option for me since I don't have an Stock Android 12 OnePlus device. I got old OnePlus devices with custom ROMs which defeats the purpose.

**Comment by LSafer** [comment]
Oh, this is a dead end then. I guess there is now only two options. Either add an optional Accessibility permission and make the app work with and without it. Or dig deeper in the decompiled OnePlus framework in search of the name of the custom permission they require.

**Comment by LSafer** [comment]
I just released [0.3-pre.6](https://github.com/LSafer/edgeseek/releases/tag/0.3-pre.6) with an optional accessibility permission. Does it fix the issue?

**Comment by jarusaurus** [comment]
Hi sorry to report even after the accessibility permission given, this issue persists. Can't control the volume. Guess OP is blocking things. Will keep you posted if this changes after some more checks.

Thanks again for this amazing project.

**Comment by PAFCicleStick** [comment]
I second the OP above, this is the log.

![Image](https://github.com/user-attachments/assets/cb8c3e6d-b136-4d06-aeae-fc8072014263)
![Image](https://github.com/user-attachments/assets/1bd686fa-dab7-48ac-a58a-1d1e04da29c9)

**Comment by titansanskargithub** [comment]
can you add adb or shizuku command for this
